### ISSUE TITLE
RocksDb

### ISSUE THREAD

**Issue by fernandes** [domodwyer/mpjbt#1]
hi @domodwyer ,

First, what amazing talk, I just found the slides yesterday and I'd say, if not the best, one of the best benchmarks between postgresql and mongodb... I always had these doubts but not enough knowledge to make a benchmark like that.

Did you benchmark against rocksdb? I don't have the same hardware you did the tests, but if I can help with the setup, package compiling or something like that just tell me.

Thank you!

**Comment by weiishann** [comment]
Hi @fernandes,

@domodwyer and myself will be speaking again in [FOSDEM 2018](https://fosdem.org/2018/schedule/). We hope to add rocksdb in the benchmark comparison this time round!

Thanks!

**Comment by fernandes** [comment]
thanks for the quick reply, waiting for the slides "update" hehehe

I wish you all the best in the presentation!

thank you!
