### ISSUE TITLE
Findings still good for 2024?

### ISSUE THREAD

**Issue by nuxcodes** [domodwyer/mpjbt#3]
Tests like [this](https://medium.com/@yurexus/can-postgresql-with-its-jsonb-column-type-replace-mongodb-30dc7feffaf3) have suggested non-trivial performance improvement for Mongo.

Wonders how the tests keep up with latest versions of Pg/Mongo.

**Comment by domodwyer** [comment]
Hey @nuxcodes, definitely not!

I know Mongo has undergone a lot of changes and performance improvements since this was put together 7 years ago!

I'd highly recommend re-evaluating if you're considering either :)

Dom
